TEXTS = {
    "uz": {
        "choose_lang": "Tilni tanlang:",
        "must_subscribe": "Botdan foydalanish uchun quyidagi kanal(lar)ga obuna bo'ling.",
        "check_sub": "Obuna bo'ldim",
        "open_channel": "Kanalga o'tish",
        "main_menu": "Asosiy menyu",
        "ask": "Savol berish",
        "upload": "Ma'lumot yuklash",
        "my_files": "Mening fayllarim",
        "history": "Tarix",
        "help": "Yordam",
        "admin": "Admin panel",
        "back": "Orqaga",
        "send_question": "Savolingizni yuboring. Men shaxsiy va ommaviy ma'lumotlardan bir vaqtda qidiraman.",
        "send_data": "Ma'lumot yuboring. PDF, DOCX, TXT, rasm, ovoz yoki oddiy matn yuborishingiz mumkin.",
        "save_where": "Saqlash turini tanlang:",
        "save_private": "Shaxsiy saqlash",
        "save_public": "Ommaviy saqlash",
        "saved_private": "Ma'lumot shaxsiy bazaga saqlandi.",
        "saved_public_pending": "Ma'lumot ommaviy bazaga yuborildi. Admin tasdiqlagach qidiruvda ko'rinadi.",
        "not_found": "Ma'lumot topilmadi.",
        "private_title": "Shaxsiy ma'lumotlardan",
        "public_title": "Ommaviy ma'lumotlardan",
        "short_answer": "Qisqa javob",
        "details": "Batafsil",
        "source": "Manba",
        "my_private_files": "Shaxsiy fayllarim",
        "my_public_files": "Ommaviy yuklaganlarim",
        "delete_file": "Faylni o'chirish",
        "recent_questions": "So'nggi savollar",
        "clear_history": "Tarixni tozalash",
        "how_it_works": "Bot qanday ishlaydi",
        "what_can_upload": "Qanday ma'lumot yuborish mumkin",
        "ask_rules": "Savol berish qoidasi",
        "about": "ManbaAI — foydalanuvchilar yuklagan ma'lumotlar asosida savollarga javob beradigan sun'iy intellekt botidir. Ushbu loyiha @ManbaAI_admin tomonidan ishlab chiqilgan.",
        "admin_dashboard": "Dashboard",
        "admin_files": "Fayllar boshqaruvi",
        "admin_users": "Foydalanuvchilar",
        "admin_moderation": "Ommaviy moderatsiya",
        "admin_exports": "Eksport",
        "admin_logs": "Loglar",
        "admin_channels": "Kanallar",
        "approved": "Tasdiqlash",
        "reject": "Rad etish",
    },
    "ru": {
        "choose_lang": "Выберите язык:",
        "must_subscribe": "Чтобы пользоваться ботом, подпишитесь на канал(ы) ниже.",
        "check_sub": "Я подписался",
        "open_channel": "Открыть канал",
        "main_menu": "Главное меню",
        "ask": "Задать вопрос",
        "upload": "Загрузить данные",
        "my_files": "Мои файлы",
        "history": "История",
        "help": "Помощь",
        "admin": "Админ панель",
        "back": "Назад",
        "send_question": "Отправьте вопрос. Я одновременно ищу в личных и публичных данных.",
        "send_data": "Отправьте данные. Можно PDF, DOCX, TXT, изображение, голос или обычный текст.",
        "save_where": "Выберите, куда сохранить:",
        "save_private": "Сохранить как личное",
        "save_public": "Сохранить как публичное",
        "saved_private": "Данные сохранены в личную базу.",
        "saved_public_pending": "Данные отправлены в публичную базу. После модерации они появятся в поиске.",
        "not_found": "Ничего не найдено.",
        "private_title": "Из личных данных",
        "public_title": "Из публичных данных",
        "short_answer": "Краткий ответ",
        "details": "Подробно",
        "source": "Источник",
        "my_private_files": "Мои личные файлы",
        "my_public_files": "Мои публичные файлы",
        "delete_file": "Удалить файл",
        "recent_questions": "Последние вопросы",
        "clear_history": "Очистить историю",
        "how_it_works": "Как работает бот",
        "what_can_upload": "Что можно загрузить",
        "ask_rules": "Как задавать вопрос",
        "about": "ManbaAI — это ИИ-бот, который отвечает на вопросы на основе загруженных пользователями данных. Проект разработан @ManbaAI_admin.",
        "admin_dashboard": "Дашборд",
        "admin_files": "Файлы",
        "admin_users": "Пользователи",
        "admin_moderation": "Модерация",
        "admin_exports": "Экспорт",
        "admin_logs": "Логи",
        "admin_channels": "Каналы",
        "approved": "Одобрить",
        "reject": "Отклонить",
    },
    "en": {
        "choose_lang": "Choose language:",
        "must_subscribe": "To use the bot, subscribe to the channel(s) below.",
        "check_sub": "I subscribed",
        "open_channel": "Open channel",
        "main_menu": "Main menu",
        "ask": "Ask a question",
        "upload": "Upload data",
        "my_files": "My files",
        "history": "History",
        "help": "Help",
        "admin": "Admin panel",
        "back": "Back",
        "send_question": "Send your question. I search personal and public data at the same time.",
        "send_data": "Send data. You can upload PDF, DOCX, TXT, image, voice, or plain text.",
        "save_where": "Choose where to save it:",
        "save_private": "Save as private",
        "save_public": "Save as public",
        "saved_private": "Saved to your private knowledge base.",
        "saved_public_pending": "Sent to the public knowledge base. It will appear in search after moderation.",
        "not_found": "No matching information found.",
        "private_title": "From private data",
        "public_title": "From public data",
        "short_answer": "Short answer",
        "details": "Details",
        "source": "Source",
        "my_private_files": "My private files",
        "my_public_files": "My public uploads",
        "delete_file": "Delete file",
        "recent_questions": "Recent questions",
        "clear_history": "Clear history",
        "how_it_works": "How the bot works",
        "what_can_upload": "What you can upload",
        "ask_rules": "Question rules",
        "about": "ManbaAI is an AI bot that answers questions based on data uploaded by users. The project was developed by @ManbaAI_admin.",
        "admin_dashboard": "Dashboard",
        "admin_files": "Files",
        "admin_users": "Users",
        "admin_moderation": "Moderation",
        "admin_exports": "Exports",
        "admin_logs": "Logs",
        "admin_channels": "Channels",
        "approved": "Approve",
        "reject": "Reject",
    },
}


def t(lang: str, key: str) -> str:
    return TEXTS.get(lang, TEXTS["uz"]).get(key, TEXTS["uz"].get(key, key))
